[Client]
	dsn = "root:nYd*4M]ipIv+@tcp(127.0.0.1:3306)/kratos?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&charset=utf8"
    	active = 20
    	idle = 10
    	idleTimeout ="4h"
    	queryTimeout = "200ms"
    	execTimeout = "300ms"
    	tranTimeout = "400ms"
